CREATE LOGIN DaniilLogin WITH PASSWORD = '1234567890bb';
CREATE LOGIN AlexeilLogin WITH PASSWORD = '123aa';
GO

CREATE USER Daniil FOR LOGIN DaniilLogin;
CREATE USER Alexei FOR LOGIN AlexeilLogin;
GO

